import type { QuizQuestionData, QuizTopicOption } from '../../components/ui/QuizCard';

export const ADMINISTRACAO_PROJETO_BANCO_DADOS_GUIDE_CONTEXT = `
GUIA DE ADMINISTRACAO E PROJETO DE BANCO DE DADOS - Topicos disponiveis:

1. DISCIPLINA E AVALIACAO: A disciplina trabalha projeto e administracao de bancos de dados com foco em Oracle. Combina teoria e laboratorio usando VirtualBox, Oracle Database, Oracle SQL Developer, Oracle SQL Developer Data Modeler e Oracle Live SQL. O programa geral inclui SQL, controle de transacoes, atividades de DBA e PL/SQL. Projeto define estrutura, regras e objetos; administracao mantem essa estrutura funcionando com usuarios, instancias, seguranca, backup, desempenho e manutencao. A avaliacao tem duas notas: N1 com projeto fase 1 (2 pts), projeto fase 2 (2 pts), prova 1 parte 1 (3 pts) e prova 1 parte 2 (3 pts); N2 com projeto fases 3, 4 e 5 (2 pts cada) e prova 2 (4 pts). O projeto em grupo e avaliado por correcao tecnica, inovacao/criatividade, complexidade/desafio e aderencia a realidade.

2. PROJETO E ESQUEMA: Um projeto de banco de dados comeca pela definicao clara do esquema, que agrupa tabelas, visoes, indices e outros objetos de uma mesma aplicacao. O esquema funciona como fronteira logica do dominio, ajudando leitura, manutencao, permissoes e evolucao. Antes de criar objetos, a ferramenta de modelagem deve ser configurada para a versao do SGBD e para os padroes esperados, pois isso influencia tipos, comportamento padrao e SQL gerado.

3. PADRONIZACAO DE NOMES: A nomenclatura fisica reduz ambiguidade e facilita manutencao. Nomes consistentes tornam o DDL mais legivel e ajudam a reconhecer o tipo de objeto em scripts, diagramas e mensagens do SGBD. Convencoes comuns incluem PK_{tabela} para chave primaria, FK_{pai}_{filho} para chave estrangeira, AK/UK para restricoes unicas, IDX para indices, CK para checks e NN para obrigatoriedade. Abreviacoes como Cod, Dta, Nom, Des, Qtd, Val e Id ajudam a manter nomes curtos e previsiveis.

4. DATA MODELER, TIPOS E DOMINIOS: O Oracle SQL Developer Data Modeler permite configurar versao do banco, colunas obrigatorias, indices de chaves estrangeiras, estilo de relacionamentos, tipos e dominios. Tipos e dominios padronizam definicoes reutilizaveis, centralizando tipo, validacao e regras recorrentes de negocio. Eles evitam que colunas semelhantes sejam definidas de formas diferentes por repeticao manual.

5. OBJETOS SQL: Tabelas devem ser criadas com colunas, chave primaria, restricoes unicas, chaves estrangeiras, obrigatoriedade e validacoes para preservar integridade. A tabela e ponto de defesa dos dados: regras no banco continuam valendo mesmo se outro sistema ou script acessar os dados. ALTER TABLE usa ADD, MODIFY e DROP COLUMN para evoluir a estrutura conforme novas regras de negocio. Comentarios documentam tabelas e colunas dentro do banco. Visoes sao consultas salvas para filtrar, simplificar, proteger ou reorganizar acesso aos dados; mudancas costumam usar CREATE OR REPLACE. Sequences geram identificadores automaticamente e reduzem preenchimento manual de chaves.

6. ARMAZENAMENTO LOGICO E FISICO NO ORACLE: O Oracle separa a organizacao logica dos dados da ocupacao fisica em disco. Essa separacao permite ao DBA reorganizar arquivos fisicos sem mudar a forma como usuarios e aplicacoes enxergam os objetos. A hierarquia logica vai de DATABASE para TABLESPACE, SEGMENTO, EXTENT e ORACLE DATA BLOCK. O bloco e a menor unidade gerenciada pelo Oracle; leituras e gravacoes acontecem em multiplos de blocos definidos por DB_BLOCK_SIZE. O bloco possui cabecalho com metadados e informacoes transacionais, area de dados e espaco livre controlado por PCTFREE e PCTUSED. PCTFREE reserva espaco para updates que aumentam linhas; PCTUSED define quando um bloco volta a aceitar inserts apos delecoes. Extent e um conjunto contiguo de blocos alocado quando um objeto precisa crescer. Segmento e o conjunto de extents de um objeto, como tabela, indice, temporario ou UNDO. Tablespace agrupa segmentos e ajuda organizacao, desempenho, manutencao e controle de espaco. Fisicamente, cada tablespace e composto por um ou mais datafiles, arquivos reais do sistema operacional onde os blocos sao gravados. A aplicacao enxerga objetos e tablespaces; o sistema operacional enxerga datafiles.

7. INDICES E PARTICIONAMENTO: Indices aceleram consultas ao oferecer caminhos de acesso alternativos, mas ocupam espaco e geram custo de manutencao em escritas. B-tree e comum em buscas seletivas e ambientes transacionais; bitmap e melhor para baixa cardinalidade e analise com muitos filtros, mas e menos adequado a muitas atualizacoes. Indices podem ser compostos, baseados em expressao, reconstruidos e monitorados para verificar se ainda trazem ganho real. Particionamento divide tabelas grandes por faixa, lista ou hash; a aplicacao continua vendo uma tabela unica, enquanto o banco administra partes menores. Indices tambem podem ser particionados para equilibrar desempenho e manutencao.

8. SEGURANCA, PERFIS E SENHAS: No Oracle, seguranca envolve identidade, privilegios, limites, auditoria, backup e recuperacao. PROFILE agrupa politicas de senha e limites de recurso, podendo ser atribuido no CREATE USER ou ALTER USER. O perfil DEFAULT sempre existe e serve como politica base. Role concede privilegio; profile impoe limite. Regras comuns de senha incluem FAILED_LOGIN_ATTEMPTS, PASSWORD_LOCK_TIME, PASSWORD_LIFE_TIME, PASSWORD_GRACE_TIME, PASSWORD_REUSE_TIME, PASSWORD_REUSE_MAX e PASSWORD_VERIFY_FUNCTION.

9. LIMITES, LOGMINER E FLASHBACK: Perfis tambem controlam recursos por sessao ou por chamada, como SESSIONS_PER_USER, CONNECT_TIME, IDLE_TIME, CPU_PER_SESSION, CPU_PER_CALL, LOGICAL_READS_PER_SESSION e LOGICAL_READS_PER_CALL; RESOURCE_LIMIT precisa estar ativo para enforcement. LogMiner analisa redo logs, usa supplemental logging e consulta V$LOGMNR_CONTENTS para reconstruir SQL_REDO e SQL_UNDO. Flashback corrige falhas logicas: Flashback Query consulta dados antigos por SCN/timestamp, Flashback Table volta uma tabela no tempo, Flashback Drop recupera objetos do recycle bin, Flashback Data Archive guarda historico longo e Flashback Transaction pode desfazer transacoes.

10. BACKUP, RECOVERY E DESASTRES: Data Pump faz backup logico com expdp/impdp para schemas, tabelas, tablespaces ou banco completo, usando DIRECTORY, DUMPFILE, LOGFILE, SCHEMAS, TABLES, REMAP_SCHEMA, QUERY e EXCLUDE. RMAN faz backup fisico de datafiles, archived redo logs, control file, SPFILE e FRA, com politicas de retencao, backup full e incremental. RESTORE recupera arquivos; RECOVER aplica logs para consistencia. DRP define continuidade por RTO e RPO, combinando RMAN, Flashback, Data Guard, Active Data Guard, RAC, TDE, LogMiner e site alternativo conforme o tipo de falha.

11. PLANO DE RECUPERACAO DE DESASTRES: O DRP organiza respostas para indisponibilidade relevante, falha de infraestrutura, perda de midia e desastre no data center. RTO mede o tempo maximo aceitavel para voltar a operar; RPO mede a perda maxima aceitavel de dados. Continuidade se relaciona aos pilares CIA: confidencialidade, integridade e disponibilidade. Falha de instancia pode ser tratada por recuperacao automatica, perda de midia por restore/recover, e catastrofe por site alternativo, redundancia e replicacao remota. Solucoes Oracle citadas incluem SMON, Active Data Guard, Oracle RAC, RMAN, Data Guard, TDE, Flashback e LogMiner.

12. RELACAO ENTRE RECURSOS E INCIDENTES: Perfis e limites reduzem abuso e mau uso; Flashback resolve erros logicos recentes; LogMiner apoia auditoria e reconstrucao de alteracoes; Data Pump atende migracoes e copias logicas; RMAN cobre falhas fisicas; Data Guard e RAC apoiam continuidade; DRP combina essas camadas em um plano operacional. As ferramentas nao competem, elas se complementam conforme impacto, granularidade e tempo de recuperacao.

13. ESTUDO POR CENARIO: Para fixar o conteudo, associe incidente a ferramenta. Atualizacao errada aponta para Flashback Query, Flashback Table ou LogMiner. Usuario sobrecarregando o banco aponta para PROFILE e Resource Manager. Migrar um schema aponta para Data Pump. Perda de arquivo fisico aponta para RMAN. Perda do site inteiro aponta para DRP com Data Guard, RAC e site remoto. Essa leitura por cenario evita decorar siglas isoladas.

14. ARQUITETURA ORACLE: A instancia Oracle e formada por estruturas de memoria e processos em execucao; o banco de dados e o conjunto de arquivos fisicos em disco. User Process fica no lado cliente; Server Process atende a requisicao no servidor e usa uma PGA privada. A SGA e memoria compartilhada da instancia e inclui Shared Pool, Database Buffer Cache e Redo Log Buffer. Shared Pool guarda SQL/PLSQL interpretado e metadados; Buffer Cache guarda blocos lidos do disco e blocos sujos; Redo Log Buffer registra alteracoes antes do LGWR gravar nos redo logs. Em leituras repetidas, SQL e blocos podem ser reaproveitados em memoria, reduzindo parse e I/O fisico. Estados praticos como clean, dirty e pinned ajudam a entender por que o Oracle posterga gravacoes de dados, mas nao posterga a persistencia do redo necessario ao COMMIT.

15. PROCESSOS E ARQUIVOS: Background processes mantem a instancia. SMON recupera a instancia apos falha; PMON limpa sessoes quebradas; DBWn grava blocos sujos nos datafiles; LGWR grava redo log buffer nos online redo logs em commit, a cada 3 segundos, com buffer cheio ou antes de checkpoint; CKPT atualiza cabecalhos de datafiles e control file; ARCn arquiva redo logs em ARCHIVELOG; MMAN gerencia memoria; RVWR apoia Flashback Database. Arquivos principais incluem control files, datafiles e redo log files; associados incluem PFILE, SPFILE, password file, archived redo logs, trace files e alert log.

16. MULTITENANT, DICIONARIO E MONITORAMENTO: No Oracle 12c+, um CDB contem CDB$ROOT, PDB$SEED e PDBs de usuario; SHOW CON_NAME e V$PDBS ajudam a confirmar o container antes de criar objetos. O dicionario de dados e mantido pelo Oracle, pertence ao SYS e fica na SYSTEM; DBA_xxx mostra todos os objetos, ALL_xxx mostra objetos acessiveis e USER_xxx mostra objetos do usuario atual. Visoes V$ mostram estado dinamico da instancia, como V$INSTANCE, V$DATABASE, V$SESSION, V$TABLESPACE, V$SPPARAMETER, V$VERSION e V$DIAG_INFO. Monitoramento combina dicionario, V$, estatisticas, DBMS_STATS, objetos INVALID, indices UNUSABLE, bloqueios, eventos de espera, operacoes longas em V$SESSION_LONGOPS e, em ultimo caso, encerramento controlado de sessoes.

17. AWR, ADDM E ADVISORS: AWR armazena snapshots de estatisticas em tabelas fisicas, com MMON e MMNL coletando metricas; STATISTICS_LEVEL e CONTROL_MANAGEMENT_PACK_ACCESS controlam disponibilidade. ADDM analisa snapshots do AWR, identifica gargalos e recomenda acoes para reduzir DB Time. Advisors especializados incluem SQL Tuning Advisor, SQL Access Advisor, MTTR Advisor, Segment Advisor, Memory Advisor e Undo Management Advisor; resultados aparecem em DBA_ADVISOR_TASKS, DBA_ADVISOR_FINDINGS, DBA_ADVISOR_RECOMMENDATIONS, DBA_ADVISOR_ACTIONS e DBA_ADVISOR_RATIONALE.

18. GERENCIAMENTO DA INSTANCIA: Oracle Net Services conecta cliente e servidor. Listener escuta conexoes na porta 1521 e e gerenciado por lsnrctl; nomes podem ser resolvidos por tnsnames.ora, EZCONNECT e sqlnet.ora. Diagnostico de conexao segue ordem logica: testar instancia e listener no servidor, depois ping, tnsping, rota de rede e TNS_ADMIN no cliente. STARTUP passa por NOMOUNT, MOUNT e OPEN: NOMOUNT le parametros e cria SGA/processos; MOUNT abre control files; OPEN abre datafiles e redo logs. Variantes como STARTUP FORCE, STARTUP OPEN READ ONLY, STARTUP RESTRICT e STARTUP PFILE atendem cenarios administrativos especificos. SHUTDOWN NORMAL espera usuarios sairem, TRANSACTIONAL espera transacoes terminarem, IMMEDIATE faz rollback e encerra limpo, ABORT derruba abruptamente e exige crash recovery pelo SMON. Alert log e trace files sao referencia central para erros criticos e eventos administrativos. Em multitenant, STARTUP abre o CDB e PDBs podem precisar de ALTER PLUGGABLE DATABASE ... OPEN ou SAVE STATE.

19. PLSQL: PL/SQL e a extensao procedural do SQL no Oracle, usada para concentrar regras de negocio no lado servidor e reduzir trafego entre cliente e banco quando ha processamento intensivo sobre dados. Todo codigo e organizado em blocos com secoes DECLARE, BEGIN, EXCEPTION e END; blocos podem ser anonimos ou armazenados como procedures, functions, packages e triggers. Variaveis, constantes, records, arrays associativos e cursores devem ser declarados antes do uso; %TYPE e %ROWTYPE reaproveitam tipos ja existentes para reduzir inconsistencias. Controle de fluxo usa IF, CASE, LOOP, WHILE, FOR, EXIT e labels. SELECT em PL/SQL exige INTO e deve retornar exatamente uma linha; multiplas linhas pedem cursores explicitos ou cursor FOR loop. DML, COMMIT, ROLLBACK e SAVEPOINT funcionam dentro dos blocos. Excecoes podem ser predefinidas, nomeadas com PRAGMA EXCEPTION_INIT ou criadas pelo usuario; SQLCODE, SQLERRM e RAISE_APPLICATION_ERROR apoiam tratamento e mensagens. Procedures executam acoes, functions retornam valor, packages agrupam interface e implementacao, transacoes autonomas isolam logs e triggers executam automaticamente em eventos DML ou DDL para auditoria e validacao.
`;

export const ADMINISTRACAO_PROJETO_BANCO_DADOS_TOPICS: QuizTopicOption[] = [
  {
    value: 'intro',
    label: 'Introdução e avaliação',
    prompt: 'Disciplina APBD, foco em Oracle, ferramentas, blocos do conteúdo programático, composição das notas e critérios do projeto.',
  },
  {
    value: 'projeto-esquema',
    label: 'Projeto e esquema',
    prompt: 'Definição de esquema, organização dos objetos da aplicação, configuração inicial da ferramenta e influência da versão do SGBD.',
  },
  {
    value: 'nomenclatura',
    label: 'Padronização de nomes',
    prompt: 'Convenções de nomes para tabelas, colunas, chaves primárias, chaves estrangeiras, restrições, índices e abreviações.',
  },
  {
    value: 'objetos-sql',
    label: 'Objetos SQL',
    prompt: 'Criação e alteração de tabelas, constraints, comentários, visões, sequences e uso de NEXTVAL/CURRVAL.',
  },
  {
    value: 'armazenamento',
    label: 'Armazenamento Oracle',
    prompt: 'Estrutura lógica e física do Oracle: blocos, PCTFREE, PCTUSED, extents, segmentos, tablespaces e datafiles.',
  },
  {
    value: 'desempenho',
    label: 'Índices e particionamento',
    prompt: 'Índices B-tree, bitmap, índices por expressão, monitoramento, reconstrução, particionamento por faixa, lista e hash.',
  },
  {
    value: 'seguranca',
    label: 'Segurança e recuperação',
    prompt: 'Perfis, políticas de senha, limites de recursos, LogMiner, Flashback, Data Pump, RMAN, RTO, RPO e recuperação de desastres.',
  },
  {
    value: 'arquitetura',
    label: 'Arquitetura Oracle',
    prompt: 'Instância, SGA, PGA, background processes, arquivos físicos, Multitenant, dicionário de dados, V$, AWR, ADDM, Oracle Net, startup e shutdown.',
  },
  {
    value: 'plsql',
    label: 'PL/SQL',
    prompt: 'Blocos PL/SQL, variáveis, %TYPE, %ROWTYPE, IF, CASE, loops, SELECT INTO, cursores, records, arrays associativos, exceções, procedures, functions, packages, transações autônomas e triggers.',
  },
];

export const ADMINISTRACAO_PROJETO_BANCO_DADOS_SECTIONS = [
  { id: 'intro', title: 'Introdução à Disciplina', shortTitle: 'Introdução', exam: 'P1' },
  { id: 'modelagem', title: 'Modelagem de Dados', shortTitle: 'Modelagem', exam: 'P1' },
  { id: 'armazenamento', title: 'Armazenamento Oracle', shortTitle: 'Armazenamento', exam: 'P1' },
  { id: 'objetos', title: 'Objetos SQL', shortTitle: 'Objetos SQL', exam: 'P1' },
  { id: 'desempenho', title: 'Desempenho e Particionamento', shortTitle: 'Desempenho', exam: 'P1' },
  { id: 'seguranca', title: 'Segurança e Recuperação', shortTitle: 'Segurança', exam: 'P2' },
  { id: 'arquitetura', title: 'Arquitetura e Administração Oracle', shortTitle: 'Arquitetura', exam: 'P2' },
  { id: 'plsql', title: 'PL/SQL no Oracle', shortTitle: 'PL/SQL', exam: 'P2' },
  { id: 'quiz', title: 'Quiz de Revisão', shortTitle: 'Quiz' },
  { id: 'iaquiz', title: 'Quiz com IA', shortTitle: 'Quiz IA' },
];

export const ADMINISTRACAO_PROJETO_BANCO_DADOS_QUIZ_DATA: QuizQuestionData[] = [
  {
    id: 'apbd-q1',
    exam: 'prova1',
    question: '1. Qual é o foco prático da disciplina Administração e Projeto de Banco de Dados?',
    options: [
      'Projetar e administrar bancos de dados usando principalmente a plataforma Oracle',
      'Estudar apenas teoria de normalização, sem laboratório',
      'Desenvolver interfaces web para consumo de APIs',
      'Substituir SQL por planilhas e relatórios manuais',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. A disciplina combina teoria e prática em laboratório com Oracle e ferramentas relacionadas.',
    feedbackWrong: 'O foco é projetar e administrar bancos de dados com Oracle, combinando teoria e prática.',
  },
  {
    id: 'apbd-q2',
    exam: 'prova1',
    question: '2. Como a primeira nota da disciplina é composta segundo o material?',
    options: [
      'Somente uma prova individual de 10 pontos',
      'Duas fases de projeto valendo 2 pontos cada e duas partes de prova valendo 3 pontos cada',
      'Cinco fases de projeto, todas com o mesmo peso',
      'Projeto único de 6 pontos e seminário de 4 pontos',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. A N1 soma Projeto Fase 1, Projeto Fase 2, Prova 1 Parte 1 e Prova 1 Parte 2.',
    feedbackWrong: 'A N1 é formada por duas fases de projeto de 2 pontos e duas partes de prova de 3 pontos.',
  },
  {
    id: 'apbd-q3',
    exam: 'prova1',
    question: '3. Em um projeto de banco de dados, o que é o esquema?',
    options: [
      'Um backup temporário usado antes do commit',
      'O espaço lógico que reúne objetos da aplicação, como tabelas, visões e índices',
      'Uma consulta salva usada apenas para leitura',
      'Um comando para desfazer alterações em uma transação',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. O esquema organiza os objetos relacionados ao mesmo domínio de dados.',
    feedbackWrong: 'O esquema é o agrupamento lógico dos objetos da aplicação, como tabelas, visões e índices.',
  },
  {
    id: 'apbd-q4',
    exam: 'prova1',
    question: '4. Por que configurar a versão do SGBD no Data Modeler antes de gerar o SQL?',
    options: [
      'Porque a versão influencia recursos disponíveis, tipos aceitos e formato do SQL gerado',
      'Porque impede a criação de chaves estrangeiras',
      'Porque substitui automaticamente a necessidade de modelagem',
      'Porque transforma toda tabela em visão',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. A configuração da versão evita SQL incompatível e retrabalho.',
    feedbackWrong: 'A versão do SGBD influencia recursos, tipos e formato do SQL gerado pela ferramenta.',
  },
  {
    id: 'apbd-q5',
    exam: 'prova1',
    question: '5. Qual padrão de nomenclatura está coerente com uma chave estrangeira?',
    options: ['PK_CLIENTE', 'FK_CLIENTE_PEDIDO', 'CK_PEDIDO_STATUS', 'IDX_PEDIDO_DATA'],
    correctIndex: 1,
    feedbackCorrect: 'Correto. FK_{pai}_{filho} é um padrão frequente para chaves estrangeiras.',
    feedbackWrong: 'Para chave estrangeira, o padrão indicado é semelhante a FK_{pai}_{filho}.',
  },
  {
    id: 'apbd-q6',
    exam: 'prova1',
    question: '6. Qual é a principal vantagem de usar domínios na modelagem?',
    options: [
      'Eliminar todas as restrições de integridade',
      'Padronizar tipo, validação e regra recorrente em várias colunas',
      'Criar automaticamente backups do banco',
      'Executar consultas sem necessidade de índices',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. Domínios reduzem repetição e inconsistência em definições comuns.',
    feedbackWrong: 'Domínios servem para padronizar definições reutilizáveis, como tipo e validação.',
  },
  {
    id: 'apbd-q7',
    exam: 'prova1',
    question: '7. Ao criar uma tabela robusta, quais elementos devem ser considerados além da lista de colunas?',
    options: [
      'Somente o nome físico da tabela',
      'Chave primária, restrições únicas, chaves estrangeiras, obrigatoriedade e validações',
      'Apenas a ordem visual das caixas no diagrama',
      'Somente comentários, sem constraints',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. Essas regras fazem o banco proteger a integridade dos dados.',
    feedbackWrong: 'A tabela deve nascer com regras de integridade, como PK, FK, unique, not null e checks.',
  },
  {
    id: 'apbd-q8',
    exam: 'prova1',
    question: '8. Qual comando é usado no Oracle para alterar a definição de uma tabela já existente?',
    options: ['CREATE VIEW', 'ALTER TABLE', 'NEXTVAL', 'COMMIT'],
    correctIndex: 1,
    feedbackCorrect: 'Correto. ALTER TABLE permite ADD, MODIFY e DROP COLUMN.',
    feedbackWrong: 'Para modificar uma tabela existente, usa-se ALTER TABLE.',
  },
  {
    id: 'apbd-q9',
    exam: 'prova1',
    question: '9. Qual descrição melhor define uma visão em banco de dados?',
    options: [
      'Uma sequência de números para chave primária',
      'Uma consulta salva que apresenta dados de forma lógica sem armazená-los diretamente',
      'Um índice obrigatório para toda chave estrangeira',
      'Uma partição física criada apenas por hash',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. A visão funciona como camada lógica de leitura ou acesso.',
    feedbackWrong: 'Uma visão é uma consulta salva usada para filtrar, simplificar ou proteger o acesso aos dados.',
  },
  {
    id: 'apbd-q10',
    exam: 'prova1',
    question: '10. Para que uma sequence é usada no Oracle?',
    options: [
      'Gerar valores numéricos únicos de forma automática',
      'Criar comentários para colunas',
      'Dividir dados por regiões geográficas',
      'Impedir qualquer atualização em uma tabela',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Sequences são comuns para gerar identificadores usados em chaves.',
    feedbackWrong: 'Sequences geram números automaticamente, normalmente consumidos com NEXTVAL.',
  },
  {
    id: 'apbd-q11',
    exam: 'prova1',
    question: '11. Em qual cenário um índice bitmap tende a ser mais adequado?',
    options: [
      'Tabela transacional com coluna altamente seletiva e muitas atualizações',
      'Coluna de baixa cardinalidade em consultas analíticas com combinação de filtros',
      'Tabela pequena que nunca é consultada',
      'Coluna de texto livre com valores praticamente únicos',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. Bitmap combina com baixa cardinalidade e cargas mais analíticas.',
    feedbackWrong: 'Bitmap é mais apropriado para baixa cardinalidade e consultas analíticas com vários filtros.',
  },
  {
    id: 'apbd-q12',
    exam: 'prova1',
    question: '12. Qual é a finalidade do particionamento de tabelas?',
    options: [
      'Dividir dados em partes menores para facilitar gestão e melhorar desempenho',
      'Remover a necessidade de chaves primárias',
      'Transformar tabelas em sequences',
      'Desativar constraints para acelerar inserts',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. A aplicação continua vendo uma tabela única, mas o banco administra partes menores.',
    feedbackWrong: 'Particionamento divide dados em partes menores, ajudando consultas, cargas e manutenção.',
  },
  {
    id: 'apbd-q13',
    exam: 'prova1',
    question: '13. Qual é a principal diferença entre armazenamento lógico e físico no Oracle?',
    options: [
      'O lógico organiza objetos como tablespaces, segmentos, extents e blocos; o físico corresponde aos datafiles no sistema operacional',
      'O lógico existe apenas em planilhas; o físico existe apenas no SQL Developer',
      'O lógico guarda somente backups; o físico guarda somente comentários de tabelas',
      'O lógico é usado apenas por usuários finais; o físico é usado apenas por visões',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O Oracle separa a forma lógica de organização da gravação física em arquivos de dados.',
    feedbackWrong: 'A diferença central é que a organização lógica envolve tablespaces, segmentos, extents e blocos, enquanto a física envolve datafiles.',
  },
  {
    id: 'apbd-q14',
    exam: 'prova1',
    question: '14. Na hierarquia lógica do Oracle, qual é a menor unidade de armazenamento gerenciada pelo banco?',
    options: ['Tablespace', 'Segmento', 'Extent', 'Oracle Data Block'],
    correctIndex: 3,
    feedbackCorrect: 'Correto. O Oracle lê e grava dados em múltiplos de blocos de dados.',
    feedbackWrong: 'A menor unidade gerenciada pelo Oracle é o Oracle Data Block, definido por parâmetros como DB_BLOCK_SIZE.',
  },
  {
    id: 'apbd-q15',
    exam: 'prova1',
    question: '15. Para que serve o parâmetro PCTFREE em um bloco de dados?',
    options: [
      'Reservar uma porcentagem do bloco para futuros updates que aumentem o tamanho das linhas',
      'Definir quantos datafiles um tablespace pode ter',
      'Determinar o nome físico de uma tabela',
      'Criar automaticamente segmentos temporários para ORDER BY',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. PCTFREE evita que o bloco fique totalmente ocupado por inserts e falte espaço para crescimento de linhas.',
    feedbackWrong: 'PCTFREE mantém uma reserva de espaço livre no bloco para updates que aumentem as linhas existentes.',
  },
  {
    id: 'apbd-q16',
    exam: 'prova1',
    question: '16. Em um bloco com PCTFREE = 20, quando o Oracle deixa de inserir novas linhas nesse bloco?',
    options: [
      'Quando o bloco chega a aproximadamente 80% de ocupação, preservando 20% livre',
      'Quando o bloco chega a exatamente 20% de ocupação total',
      'Somente quando o tablespace fica offline',
      'Apenas depois que todos os datafiles são removidos',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Com PCTFREE = 20, o bloco deixa de receber novos inserts quando a reserva livre chega ao limite de 20%.',
    feedbackWrong: 'Com PCTFREE = 20, o Oracle preserva 20% do bloco para updates; novas inserções param por volta de 80% de uso.',
  },
  {
    id: 'apbd-q17',
    exam: 'prova1',
    question: '17. O que é um extent no armazenamento Oracle?',
    options: [
      'Um conjunto contíguo de blocos alocado para um objeto quando ele precisa de mais espaço',
      'Um arquivo físico que substitui todos os datafiles',
      'Uma consulta salva usada para esconder colunas sensíveis',
      'Uma restrição de integridade criada com CHECK',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O Oracle aloca espaço em extents, não bloco por bloco de forma isolada.',
    feedbackWrong: 'Extent é um conjunto contíguo de blocos; segmentos crescem pela alocação de novos extents.',
  },
  {
    id: 'apbd-q18',
    exam: 'prova1',
    question: '18. Por que separar tablespaces de dados e índices pode ser útil em um projeto Oracle?',
    options: [
      'Porque permite organizar segmentos, distribuir carga de I/O, facilitar manutenção e controlar espaço',
      'Porque elimina a necessidade de chaves primárias e estrangeiras',
      'Porque transforma todos os índices em visões materializadas',
      'Porque impede que o DBA gerencie datafiles',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Tablespaces ajudam organização lógica e podem apoiar desempenho, manutenção e controle de espaço.',
    feedbackWrong: 'Separar tablespaces ajuda a organizar segmentos, administrar espaço e, quando bem planejado, distribuir carga física.',
  },
  {
    id: 'apbd-q19',
    exam: 'prova2',
    question: '19. No Oracle, qual é o papel principal de um PROFILE?',
    options: [
      'Agrupar políticas de senha e limites de consumo de recursos para usuários',
      'Substituir uma role e conceder privilégios de objeto automaticamente',
      'Executar restore físico de datafiles corrompidos',
      'Criar uma visão para esconder colunas sensíveis',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. PROFILE é um pacote de política: controla senha e limites, mas não concede privilégios como uma role.',
    feedbackWrong: 'PROFILE não é role. Ele impõe regras de senha e recursos; privilégios são concedidos por grants e roles.',
  },
  {
    id: 'apbd-q20',
    exam: 'prova2',
    question: '20. O que acontece quando um usuário é criado sem profile explícito?',
    options: [
      'A conta fica sem qualquer política de senha',
      'O Oracle aplica automaticamente o profile DEFAULT',
      'O usuário recebe privilégios de DBA',
      'A conta só pode conectar pelo RMAN',
    ],
    correctIndex: 1,
    feedbackCorrect: 'Correto. DEFAULT sempre existe, não pode ser eliminado e funciona como política base.',
    feedbackWrong: 'Usuários sem profile explícito recebem o DEFAULT, que pode ser ajustado pelo DBA.',
  },
  {
    id: 'apbd-q21',
    exam: 'prova2',
    question: '21. Qual combinação trata excesso de tentativas de login no profile?',
    options: [
      'FAILED_LOGIN_ATTEMPTS e PASSWORD_LOCK_TIME',
      'PCTFREE e PCTUSED',
      'RESTORE e RECOVER',
      'SCHEMAS e TABLES',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Um define a quantidade de falhas; o outro define o tempo de bloqueio da conta.',
    feedbackWrong: 'Bloqueio por tentativas usa FAILED_LOGIN_ATTEMPTS junto de PASSWORD_LOCK_TIME.',
  },
  {
    id: 'apbd-q22',
    exam: 'prova2',
    question: '22. Por que PASSWORD_VERIFY_FUNCTION é útil?',
    options: [
      'Porque valida regras de complexidade antes de aceitar a troca de senha',
      'Porque recupera uma tabela apagada do recycle bin',
      'Porque gera dump físico dos datafiles',
      'Porque ativa automaticamente Data Guard',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. A função PL/SQL pode exigir tamanho mínimo, tipos de caracteres e diferença em relação à senha antiga.',
    feedbackWrong: 'PASSWORD_VERIFY_FUNCTION valida a senha antes da alteração; não é mecanismo de backup ou replicação.',
  },
  {
    id: 'apbd-q23',
    exam: 'prova2',
    question: '23. Qual parâmetro global precisa estar ativo para que limites de recursos do profile sejam aplicados?',
    options: ['RESOURCE_LIMIT', 'DB_BLOCK_SIZE', 'OPEN_RESETLOGS', 'NEXTVAL'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Definir limites no profile não basta se o enforcement global de recursos estiver desligado.',
    feedbackWrong: 'Os limites de recursos dependem de RESOURCE_LIMIT ativo no banco.',
  },
  {
    id: 'apbd-q24',
    exam: 'prova2',
    question: '24. Em que situação o LogMiner é especialmente adequado?',
    options: [
      'Investigar redo logs para descobrir SQL executado e possível SQL de desfazer',
      'Criar índices bitmap em colunas de baixa cardinalidade',
      'Trocar a senha expirada de todos os usuários',
      'Separar tablespaces de dados e índices',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. LogMiner reconstrói a história de alterações a partir dos redo logs.',
    feedbackWrong: 'LogMiner é usado para analisar redo logs, consultar V$LOGMNR_CONTENTS e obter SQL_REDO/SQL_UNDO.',
  },
  {
    id: 'apbd-q25',
    exam: 'prova2',
    question: '25. Qual recurso permite consultar uma tabela como ela estava em um timestamp ou SCN anterior?',
    options: ['Flashback Query', 'Data Pump', 'Oracle RAC', 'CREATE DIRECTORY'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Flashback Query permite comparar o estado atual com um ponto anterior sem restore completo.',
    feedbackWrong: 'Consultar dados antigos por timestamp ou SCN é função do Flashback Query.',
  },
  {
    id: 'apbd-q26',
    exam: 'prova2',
    question: '26. Quando Flashback Table costuma ser uma boa escolha?',
    options: [
      'Quando uma tabela sofreu UPDATE ou DELETE indevido e precisa voltar a um ponto anterior',
      'Quando o data center inteiro ficou indisponível',
      'Quando é preciso criar uma sequence para chave artificial',
      'Quando se deseja conceder privilégios a uma role',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Flashback Table é uma recuperação lógica mais cirúrgica para uma tabela afetada.',
    feedbackWrong: 'Flashback Table volta uma tabela a um ponto anterior, normalmente exigindo ROW MOVEMENT habilitado.',
  },
  {
    id: 'apbd-q27',
    exam: 'prova2',
    question: '27. Qual afirmação diferencia Data Pump de RMAN?',
    options: [
      'Data Pump trabalha no nível lógico de objetos; RMAN trabalha no nível físico de arquivos e recuperação',
      'Data Pump aplica archived redo logs; RMAN só exporta linhas em CSV',
      'Data Pump substitui roles; RMAN substitui profiles',
      'Data Pump só recupera senhas; RMAN só cria visões',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Data Pump exporta/importa objetos; RMAN cobre backup físico, restore e recover.',
    feedbackWrong: 'Data Pump é backup/migração lógica com expdp/impdp; RMAN é backup e recovery físico.',
  },
  {
    id: 'apbd-q28',
    exam: 'prova2',
    question: '28. Qual é a diferença entre RESTORE e RECOVER no RMAN?',
    options: [
      'RESTORE traz arquivos do backup; RECOVER aplica logs para reconstruir consistência',
      'RESTORE cria usuários; RECOVER cria profiles',
      'RESTORE consulta redo logs; RECOVER exporta schemas',
      'RESTORE habilita ROW MOVEMENT; RECOVER cria recycle bin',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Restore recupera arquivos; recover avança esses arquivos com logs até o ponto necessário.',
    feedbackWrong: 'No RMAN, RESTORE e RECOVER são etapas diferentes: arquivo primeiro, consistência depois.',
  },
  {
    id: 'apbd-q29',
    exam: 'prova2',
    question: '29. Em um plano de recuperação de desastres, o que RTO mede?',
    options: [
      'O tempo máximo aceitável para voltar a operar',
      'A quantidade máxima de dados que pode ser perdida',
      'O número de sessões simultâneas por usuário',
      'A porcentagem livre reservada no bloco',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. RTO orienta quanto tempo o negócio aceita ficar indisponível.',
    feedbackWrong: 'RTO mede tempo de recuperação. A perda máxima aceitável de dados é RPO.',
  },
  {
    id: 'apbd-q30',
    exam: 'prova2',
    question: '30. Se a prioridade é reduzir a perda máxima de dados em um desastre, qual métrica está em foco?',
    options: ['RPO', 'PCTFREE', 'PASSWORD_GRACE_TIME', 'COMPOSITE_LIMIT'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. RPO define a perda máxima de dados aceitável e influencia frequência de backup, archivelog e replicação.',
    feedbackWrong: 'A métrica de perda máxima aceitável de dados é RPO; RTO trata do tempo para voltar a operar.',
  },
  {
    id: 'apbd-q31',
    exam: 'prova2',
    question: '31. Qual alternativa diferencia corretamente instância Oracle e banco de dados?',
    options: [
      'Instância é memória e processos; banco de dados é o conjunto de arquivos físicos em disco',
      'Instância é apenas um datafile; banco de dados é apenas uma sessão de usuário',
      'Instância contém somente tabelas; banco de dados contém apenas processos de background',
      'Instância é o arquivo tnsnames.ora; banco de dados é o listener',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. A instância coordena operações em memória; o banco persiste dados em arquivos.',
    feedbackWrong: 'No Oracle, instância é SGA mais processos; banco de dados é o conjunto de control files, datafiles, redo logs e arquivos associados.',
  },
  {
    id: 'apbd-q32',
    exam: 'prova2',
    question: '32. Qual componente da SGA armazena blocos de dados lidos do disco e pode conter dirty blocks?',
    options: ['Database Buffer Cache', 'Shared Pool', 'Redo Log Buffer', 'PFILE'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O Database Buffer Cache mantém blocos em memória; blocos alterados e ainda não gravados são dirty blocks.',
    feedbackWrong: 'Blocos de dados ficam no Database Buffer Cache. Shared Pool guarda SQL/metadados; Redo Log Buffer guarda registros de alteração.',
  },
  {
    id: 'apbd-q33',
    exam: 'prova2',
    question: '33. Por que o LGWR é crítico para a durabilidade das transações?',
    options: [
      'Porque grava entradas do Redo Log Buffer nos redo logs antes de confirmar o COMMIT ao cliente',
      'Porque cria novos PDBs automaticamente',
      'Porque armazena o dicionário de dados na tablespace SYSTEM',
      'Porque resolve aliases do tnsnames.ora',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O COMMIT só é confirmado depois que o redo necessário foi gravado pelo LGWR.',
    feedbackWrong: 'LGWR garante durabilidade gravando redo em disco; criação de PDB, dicionário e aliases são outras camadas.',
  },
  {
    id: 'apbd-q34',
    exam: 'prova2',
    question: '34. Qual processo limpa recursos quando uma sessão cai abruptamente?',
    options: ['PMON', 'DBWn', 'ARCn', 'CKPT'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. PMON limpa recursos, libera locks e trata sessões quebradas.',
    feedbackWrong: 'PMON é o processo associado à limpeza de sessões problemáticas; DBWn grava blocos, ARCn arquiva redo e CKPT registra checkpoints.',
  },
  {
    id: 'apbd-q35',
    exam: 'prova2',
    question: '35. Qual arquivo é indispensável para a instância saber a estrutura física do banco?',
    options: ['Control file', 'Trace file', 'tnsnames.ora', 'Alert log'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O control file guarda a localização dos datafiles e redo logs e é essencial para montar o banco.',
    feedbackWrong: 'O arquivo crítico para estrutura física é o control file; por isso ele deve ser multiplexado.',
  },
  {
    id: 'apbd-q36',
    exam: 'prova2',
    question: '36. Em arquitetura Multitenant, qual é o papel do PDB$SEED?',
    options: [
      'Servir como template somente leitura para criação de novos PDBs',
      'Guardar apenas redo logs online',
      'Executar o Listener na porta 1521',
      'Substituir o CDB$ROOT como container principal',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O PDB$SEED é um modelo usado para provisionar novos pluggable databases.',
    feedbackWrong: 'PDB$SEED é o template somente leitura. O CDB$ROOT guarda metadados comuns e PDBs de usuário abrigam aplicações.',
  },
  {
    id: 'apbd-q37',
    exam: 'prova2',
    question: '37. Qual família de visões do dicionário mostra apenas objetos pertencentes ao usuário atual?',
    options: ['USER_xxx', 'ALL_xxx', 'DBA_xxx', 'V$xxx'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. USER_xxx limita o escopo aos objetos do próprio usuário.',
    feedbackWrong: 'USER_xxx mostra objetos do usuário atual; ALL_xxx mostra objetos acessíveis; DBA_xxx mostra tudo com privilégio adequado.',
  },
  {
    id: 'apbd-q38',
    exam: 'prova2',
    question: '38. Qual visão é adequada para identificar sessões bloqueadas por outras sessões?',
    options: ['V$SESSION', 'DBA_TABLES', 'USER_OBJECTS', 'V$VERSION'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. V$SESSION expõe sessões, estado, espera e coluna blocking_session.',
    feedbackWrong: 'Sessões e bloqueios são observados em V$SESSION, não em visões de metadados de tabelas.',
  },
  {
    id: 'apbd-q39',
    exam: 'prova2',
    question: '39. Qual ferramenta analisa snapshots do AWR e gera recomendações para reduzir DB Time?',
    options: ['ADDM', 'Data Pump', 'SQL*Plus DESCRIBE', 'Listener'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. ADDM usa snapshots do AWR para apontar gargalos e recomendações priorizadas.',
    feedbackWrong: 'ADDM é o monitor diagnóstico baseado em AWR; Data Pump move dados, Listener recebe conexões e DESCRIBE mostra estrutura.',
  },
  {
    id: 'apbd-q40',
    exam: 'prova2',
    question: '40. No STARTUP Oracle, em qual estágio os control files são abertos, mas datafiles e redo logs ainda não?',
    options: ['MOUNT', 'NOMOUNT', 'OPEN', 'ABORT'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Em MOUNT, a instância se associa ao banco lendo os control files.',
    feedbackWrong: 'NOMOUNT lê parâmetros e cria SGA/processos; MOUNT abre control files; OPEN abre datafiles e redo logs.',
  },
  {
    id: 'apbd-q41',
    exam: 'prova2',
    question: '41. Qual modo de shutdown faz rollback das transações abertas e encerra de forma limpa?',
    options: ['SHUTDOWN IMMEDIATE', 'SHUTDOWN ABORT', 'STARTUP NOMOUNT', 'ALTER DATABASE MOUNT'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. SHUTDOWN IMMEDIATE é muito usado porque encerra limpo após rollback das transações abertas.',
    feedbackWrong: 'SHUTDOWN IMMEDIATE faz rollback e não exige recovery; ABORT derruba abruptamente e exigirá crash recovery pelo SMON.',
  },
  {
    id: 'apbd-q42',
    exam: 'prova2',
    question: '42. Qual componente permite conexões remotas ao banco escutando, por padrão, na porta 1521?',
    options: ['Listener', 'PGA', 'DBWn', 'PDB$SEED'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O Listener recebe conexões remotas e é administrado com lsnrctl.',
    feedbackWrong: 'Conexões remotas chegam pelo Listener. PGA é memória privada, DBWn grava blocos e PDB$SEED é template de PDB.',
  },
  {
    id: 'apbd-q43',
    exam: 'prova2',
    question: '43. Qual visão é mais adequada para acompanhar o progresso de operações longas como backups e rebuilds?',
    options: ['V$SESSION_LONGOPS', 'DBA_TABLESPACES', 'USER_CONSTRAINTS', 'V$LOGFILE'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. V$SESSION_LONGOPS mostra progresso, trabalho total e tempo restante estimado de operações extensas.',
    feedbackWrong: 'Operações demoradas são acompanhadas em V$SESSION_LONGOPS, não em visões estáticas de metadados.',
  },
  {
    id: 'apbd-q44',
    exam: 'prova2',
    question: '44. Qual consulta ajuda a localizar o diretório de diagnóstico usado pelo alert log e pelos trace files?',
    options: ['SELECT * FROM v$diag_info', 'SELECT * FROM dba_tables', 'SELECT * FROM user_users', 'SELECT * FROM v$tablespace'],
    correctIndex: 0,
    feedbackCorrect: 'Correto. V$DIAG_INFO expõe caminhos de diagnóstico, incluindo trilhas ligadas ao alert log e traces.',
    feedbackWrong: 'Para localizar diretórios de diagnóstico do Oracle, a visão mais indicada é V$DIAG_INFO.',
  },
  {
    id: 'apbd-q45',
    exam: 'prova2',
    question: '45. Após executar STARTUP em um ambiente Multitenant, o que normalmente acontece com os PDBs de usuário?',
    options: [
      'Podem permanecer em MOUNTED até serem abertos explicitamente ou terem SAVE STATE configurado',
      'São sempre removidos e recriados a partir do PDB$SEED',
      'Viraram automaticamente control files de backup',
      'Passam a substituir o CDB$ROOT como container principal',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O CDB sobe, mas PDBs de usuário podem exigir ALTER PLUGGABLE DATABASE ... OPEN ou SAVE STATE.',
    feedbackWrong: 'Em Multitenant, STARTUP não garante que todos os PDBs de usuário fiquem abertos; isso depende da abertura explícita ou do estado salvo.',
  },
  {
    id: 'apbd-q46',
    exam: 'prova2',
    question: '46. Por que o Oracle pode confirmar um COMMIT antes de o bloco alterado chegar ao datafile?',
    options: [
      'Porque a durabilidade imediata é garantida pelo redo gravado pelo LGWR, enquanto o DBWn pode gravar o bloco depois',
      'Porque o Oracle ignora redo logs quando a sessão usa PGA grande',
      'Porque o Shared Pool substitui permanentemente os datafiles após o COMMIT',
      'Porque o CKPT grava o bloco diretamente no cliente antes do LGWR',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O ponto crítico do COMMIT é a gravação do redo; os dirty blocks podem ser persistidos mais tarde sem perder a consistência.',
    feedbackWrong: 'O COMMIT depende da persistência do redo pelo LGWR. O bloco de dados pode continuar apenas em memória até o DBWn gravá-lo.',
  },
  {
    id: 'apbd-q47',
    exam: 'prova2',
    question: '47. Qual estrutura representa corretamente a organização básica de um bloco PL/SQL?',
    options: [
      'DECLARE ... BEGIN ... EXCEPTION ... END',
      'CREATE ... SELECT ... FETCH ... CLOSE',
      'OPEN ... WHERE CURRENT OF ... COMMIT',
      'PACKAGE ... BODY ... TRIGGER ... ROLLBACK',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. DECLARE é opcional, BEGIN...END é obrigatório e EXCEPTION é a área de tratamento de erros.',
    feedbackWrong: 'O bloco PL/SQL é estruturado em torno de DECLARE, BEGIN, EXCEPTION e END; apenas a parte executável é obrigatória.',
  },
  {
    id: 'apbd-q48',
    exam: 'prova2',
    question: '48. Qual é a principal vantagem de declarar uma variável com `%TYPE`?',
    options: [
      'Herda o mesmo tipo de uma coluna ou variável existente, reduzindo inconsistência de manutenção',
      'Transforma a variável em cursor explícito automaticamente',
      'Permite executar COMMIT sem abrir transação',
      'Faz a variável aceitar qualquer tipo de dado sem validação',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. `%TYPE` evita duplicar a definição do tipo e acompanha mudanças na coluna referenciada.',
    feedbackWrong: '`%TYPE` serve para reaproveitar tipos já existentes, não para flexibilizar tipos indefinidamente nem criar cursores.',
  },
  {
    id: 'apbd-q49',
    exam: 'prova2',
    question: '49. Em PL/SQL, quando `SELECT ... INTO` é uma escolha segura?',
    options: [
      'Quando a consulta retorna exatamente uma linha',
      'Quando a consulta pode retornar qualquer quantidade de linhas',
      'Somente quando a consulta não usa WHERE',
      'Apenas para comandos DDL como CREATE TABLE',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Zero linhas gera `NO_DATA_FOUND` e mais de uma linha gera `TOO_MANY_ROWS`.',
    feedbackWrong: '`SELECT INTO` exige resultado único. Para múltiplas linhas, o caminho típico é usar cursores.',
  },
  {
    id: 'apbd-q50',
    exam: 'prova2',
    question: '50. Por que o cursor FOR loop costuma ser preferido ao ciclo manual OPEN/FETCH/CLOSE?',
    options: [
      'Porque o Oracle faz automaticamente a abertura, leitura e fechamento do cursor',
      'Porque ele dispensa a consulta SQL',
      'Porque ele permite COMMIT dentro de qualquer loop FOR UPDATE sem risco',
      'Porque ele substitui todas as exceções por `WHEN OTHERS`',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O cursor FOR loop reduz código repetitivo e diminui chance de erro no gerenciamento do cursor.',
    feedbackWrong: 'A principal vantagem é automatizar OPEN, FETCH e CLOSE; a consulta continua existindo e as regras transacionais não desaparecem.',
  },
  {
    id: 'apbd-q51',
    exam: 'prova2',
    question: '51. Qual alternativa descreve melhor o uso de `PRAGMA EXCEPTION_INIT`?',
    options: [
      'Dar nome a um código de erro Oracle específico para tratá-lo de forma explícita',
      'Criar uma sequence para exceções de usuário',
      'Converter uma procedure em transaction autonomous',
      'Liberar locks de cursores FOR UPDATE',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. O pragma vincula um nome PL/SQL a um erro Oracle, como ORA-02291, melhorando a clareza do handler.',
    feedbackWrong: '`PRAGMA EXCEPTION_INIT` não trata transações nem cursores; ele associa um nome a um erro Oracle para tratamento específico.',
  },
  {
    id: 'apbd-q52',
    exam: 'prova2',
    question: '52. O que diferencia uma function de uma procedure no Oracle?',
    options: [
      'A function precisa retornar um valor com RETURN; a procedure executa uma ação e pode usar parâmetros de saída',
      'A procedure sempre roda em trigger e a function nunca pode ser armazenada',
      'A function não aceita parâmetros e a procedure aceita apenas IN OUT',
      'A procedure só pode conter SQL e a function só pode conter PL/SQL puro',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Essa é a distinção central entre os dois tipos de programa armazenado.',
    feedbackWrong: 'Functions retornam valor obrigatório; procedures focam na ação e podem devolver dados por parâmetros OUT ou IN OUT.',
  },
  {
    id: 'apbd-q53',
    exam: 'prova2',
    question: '53. Em qual cenário `PRAGMA AUTONOMOUS_TRANSACTION` faz mais sentido?',
    options: [
      'Registrar log de auditoria que deve permanecer salvo mesmo se a transação principal sofrer rollback',
      'Evitar a necessidade de COMMIT em qualquer transação',
      'Substituir RMAN em backup físico',
      'Permitir que `SELECT INTO` retorne múltiplas linhas',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Transações autônomas isolam a gravação, muito úteis para log e auditoria.',
    feedbackWrong: 'O uso clássico é log independente da transação principal; isso não substitui backup nem altera o comportamento de `SELECT INTO`.',
  },
  {
    id: 'apbd-q54',
    exam: 'prova2',
    question: '54. Qual afirmação resume melhor o papel de uma trigger?',
    options: [
      'É um programa PL/SQL armazenado executado automaticamente em resposta a eventos como INSERT, UPDATE, DELETE ou DDL',
      'É uma tabela temporária criada para guardar resultados de cursores',
      'É uma função de senha usada em profiles',
      'É o mecanismo que abre PDBs após o STARTUP do CDB',
    ],
    correctIndex: 0,
    feedbackCorrect: 'Correto. Triggers automatizam reações a eventos do banco, como validações e auditoria.',
    feedbackWrong: 'Trigger é código disparado automaticamente por eventos do banco; não é estrutura temporária, profile nem mecanismo de startup.',
  },
];
